import { getProviders, signIn } from "next-auth/react";
import Head from "next/head";

function SignIn({ providers }) {
  return (
    <>
      <Head>
        <title>Login | hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hulu.svg" />
      </Head>

      <div className=" flex flex-col justify-center items-center min-h-screen py-2  px-14 text-center bg-black">
        <img
          className="w-80"
          src="https://www.billboard.com/wp-content/uploads/2021/11/hulu-logo.png"
          alt=""
        />

        <p className="font-xs text-green-500 ">
          Welcome to the hulu-clone Sign in to exlore movies!.
        </p>

        <div className="mt-40">
          {providers &&
            Object.values(providers).map((provider) => (
              <div key={provider.name}>
                <button
                  className=" p-3 button rounded-md font-semibold text-sm bg-green-500 text-black"
                  onClick={() => signIn(provider.id, { callbackUrl: "/" })}
                >
                  Sign In with {provider.name}
                </button>
              </div>
            ))}
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const providers = await getProviders();

  return {
    props: {
      providers,
    },
  };
}

export default SignIn;
